### ISSUE TITLE
Tab-bar tabs squished, can't horizontal scroll

### ISSUE THREAD

**Issue by glnster** [trevordmiller/nova-atom-syntax#17]
First off, thanks for a beautiful theme!

The issue I'm experiencing is that the tab-bar tabs are too narrow & titles illegible, when I have e.g. a dozen tabs open, per pane on my typical dual-pane view. I know how to set min-width on them, but then the issue becomes: the tab-bar isn't horizontally scrollable. I can set overflow:auto on the tab-bar, but I don't want it to use the default ugly-looking scrollbar on scroll.

<img width="636" alt="screen shot 2016-09-24 at 1 44 55 pm" src="https://cloud.githubusercontent.com/assets/230488/18811237/c0ee5d0c-825e-11e6-8927-e8d9cbb84af4.png">

thanks,
Glenn

**Comment by trevordmiller** [comment]
@glnster The Nova theme doesn't effect the rendering of tabs; that is owned by Atom. I feel this is expected behavior but you can open an issue on Atom's repo if you disagree. For example, here is the Atom Dark theme:
![image](https://cloud.githubusercontent.com/assets/5497885/18811498/952c1618-826e-11e6-9479-f28d7e69fb94.png)
